### ISSUE TITLE
Get Victor Mono cursive italics wired up

### ISSUE THREAD

**Issue by kredati** [thinking-with-computers/ludus-web#4]
Currently, anything styled "italic" is nevertheless showing up in the oblique face.

At current, this is downloaded from Google Fonts, not served statically.

Victor Mono: https://rubjo.github.io/victor-mono/

**Comment by emenel** [comment]
fixed with commit https://github.com/thinking-with-computers/ludus-web/commit/f670b0bc8c504dd8fb33032c64b1d1dfd5c310ca
